# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e2d1098aba09b355399df8277ecb630975e9b0bbeebfb664ab00920d0bd9922f8a80172f5716e704ad6bde09ff4891d64efbd2aeeb71e42c42193afa6c1196f

test:
  secret_key_base: 7eaf11133a0c6d55dac9700e55d21de452805ac5d9ebc3472ffd7c82501db49ff95df776b93034d2049da8523f3b319ca6623c31985dc8cce2bfda62fadc94e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
